import { DigestSection, DateRange } from './types';

const CATEGORY_HEADERS: Record<DigestSection['category'], string> = {
  features: 'New Features',
  fixes: 'Bug Fixes',
  improvements: 'Improvements',
  other: 'Other Changes',
};

const CATEGORY_EMOJIS: Record<DigestSection['category'], string> = {
  features: '🚀',
  fixes: '🐛',
  improvements: '⚡',
  other: '🔧',
};

/**
 * Format digest sections as Markdown
 */
export function formatMarkdown(
  sections: DigestSection[],
  dateRange: DateRange
): string {
  const lines: string[] = [];

  // Header
  lines.push('# Changelog Digest');
  lines.push('');
  lines.push(`**Period:** ${dateRange.start} → ${dateRange.end}`);
  lines.push(`**Generated:** ${new Date().toISOString()}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Sections
  const nonEmptySections = sections.filter((s) => s.items.length > 0);

  if (nonEmptySections.length === 0) {
    lines.push('*No significant changes to report in this period.*');
    lines.push('');
  } else {
    for (const section of nonEmptySections) {
      const emoji = CATEGORY_EMOJIS[section.category];
      const header = CATEGORY_HEADERS[section.category];
      lines.push(`## ${emoji} ${header}`);
      lines.push('');

      for (const item of section.items) {
        lines.push(`- ${item}`);
      }
      lines.push('');
    }
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push('*Generated by [changelog-digest](https://github.com/yourusername/changelog-digest)*');

  return lines.join('\n');
}

/**
 * Format digest sections as HTML
 */
export function formatHTML(
  sections: DigestSection[],
  dateRange: DateRange
): string {
  const lines: string[] = [];

  lines.push('<!DOCTYPE html>');
  lines.push('<html lang="en">');
  lines.push('<head>');
  lines.push('  <meta charset="UTF-8">');
  lines.push('  <meta name="viewport" content="width=device-width, initial-scale=1.0">');
  lines.push('  <title>Changelog Digest</title>');
  lines.push('  <style>');
  lines.push('    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; line-height: 1.6; }');
  lines.push('    h1 { border-bottom: 2px solid #eee; padding-bottom: 0.5rem; }');
  lines.push('    h2 { margin-top: 2rem; }');
  lines.push('    .meta { color: #666; margin-bottom: 2rem; }');
  lines.push('    ul { padding-left: 1.5rem; }');
  lines.push('    li { margin-bottom: 0.5rem; }');
  lines.push('    footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #eee; color: #999; font-size: 0.9rem; }');
  lines.push('  </style>');
  lines.push('</head>');
  lines.push('<body>');

  // Header
  lines.push('  <h1>Changelog Digest</h1>');
  lines.push('  <div class="meta">');
  lines.push(`    <strong>Period:</strong> ${dateRange.start} → ${dateRange.end}<br>`);
  lines.push(`    <strong>Generated:</strong> ${new Date().toISOString()}`);
  lines.push('  </div>');

  // Sections
  const nonEmptySections = sections.filter((s) => s.items.length > 0);

  if (nonEmptySections.length === 0) {
    lines.push('  <p><em>No significant changes to report in this period.</em></p>');
  } else {
    for (const section of nonEmptySections) {
      const emoji = CATEGORY_EMOJIS[section.category];
      const header = CATEGORY_HEADERS[section.category];
      lines.push(`  <h2>${emoji} ${header}</h2>`);
      lines.push('  <ul>');

      for (const item of section.items) {
        lines.push(`    <li>${escapeHtml(item)}</li>`);
      }
      lines.push('  </ul>');
    }
  }

  // Footer
  lines.push('  <footer>');
  lines.push('    Generated by <a href="https://github.com/yourusername/changelog-digest">changelog-digest</a>');
  lines.push('  </footer>');
  lines.push('</body>');
  lines.push('</html>');

  return lines.join('\n');
}

/**
 * Escape HTML special characters
 */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
